#输入的视频文件
input: /content/drive/MyDrive/.avi
#中间过程会生成的音频文件
output: /content/drive/MyDrive/.mp3
#生成的原始字幕文件
srt_path: /content/drive/MyDrive/.srt
#生成的翻译后的字幕文件
srt_translate_path: /content/drive/MyDrive/.srt
#翻译时开启多少线程
translate_threads: 10
#翻译源语言
from: ja
#翻译目标语言
to: en
#huggingface model地址，例如 /content/whisper-medium/pytorch_model.bin
hf_model_path: /content/whisper-medium/pytorch_model.bin
#devive: cuda, cpu
device: cuda
